### ISSUE TITLE
convert the [UInt16]

### ISSUE THREAD

**Issue by Tommynocker** [DimaRU/SampleSwiftyModbus#1]
Hi how I convert the [UInt16] to an integer?

**Comment by Tommynocker** [comment]
Example
[16789, 32884, 41251, 26229]

**Comment by DimaRU** [comment]
It depends on what exactly you want.
Examples:
```swift
let a: [UInt16] = [16789, 32884, 41251, 26229]

let i: UInt = (UInt(a[0]) << 48) | (UInt(a[1]) << 32) | (UInt(a[2]) << 16) | UInt(a[3])
print(i)
let i1 = a.reduce(0) { $0 << 16 | UInt($1) }
print(i1)
let i2 = a.withUnsafeBytes { $0.load(as: UInt64.self) }
print(String(format: "%lx", i2))
```

**Comment by Tommynocker** [comment]
I want to read the kwh form pac3200

**Comment by Tommynocker** [comment]
let a = try modbus.readRegisters(addr: 801, count: 4)
and then convert to a Number

**Comment by DimaRU** [comment]
If I understand correctly, we are talking about Siemens SENTRON PAC3200.

| Offset | Number of registers | Name | Format | Unit | Value range | Access |
| --- | --- | --- | --- | --- | --- | --- |
| 801 | 4 | Active Energy Import Tariff 1 | Double | Wh | Overflow 1.0e+12 | RW |

Based on the documentation, we should read `Double` value.
Then the code will be as follows:

```swift
let a = try modbus.readRegisters(addr: 801, count: 4)
var i = a.reduce(0) { $0 << 16 | UInt($1) }
let value = withUnsafeBytes(of: &i) {
    $0.load(as: Double.self)
}
print("Wh:", value)
```

**Comment by Tommynocker** [comment]
yes, perfect, it works. thanks

**Comment by Tommynocker** [comment]
:)
